### ISSUE TITLE
Mention Homebrew in the readme

### ISSUE THREAD

**Issue by ryandesign** [Kevin-De-Koninck/Get-It#10]
The readme doesn't mention that the required dependencies must be installed with / will be installed with Homebrew. Please mention that in the readme, so that users who wish to avoid Homebrew can avoid your software. Thanks.

**Comment by Kevin-De-Koninck** [comment]
Late to the party... Broke my hand last night so now I got the time! I'm sorry for the long wait.

**Comment by Kevin-De-Koninck** [comment]
I mentioned it as you requested it.
