### ISSUE TITLE
Tell us how to install the dependancies ourself

### ISSUE THREAD

**Issue by bhargavgv** [Kevin-De-Koninck/Get-It#13]
I want to install the dependencies myself instead of the app doing it for me, because I want to see exactly what is happening. So, could you make a list of Python modules that I need to install?

**Comment by nielsbom** [comment]
See the code here: https://github.com/Kevin-De-Koninck/Get-It/blob/14a2f4077f5f218d969c1eb7a3a1a8e3b34cf165/Get%20It/InstallationGuideTexts.swift

**Comment by bhargavgv** [comment]
I installed the dependencies, but apparently Get It doesn't actually check if the user installed it manually.

**Comment by nielsbom** [comment]
It looks like it does check, whether that code works, I couldn't tell ya :-) I didn't test it.

https://github.com/Kevin-De-Koninck/Get-It/blob/14a2f4077f5f218d969c1eb7a3a1a8e3b34cf165/Get%20It/InstallationGuideViewController.swift#L124

https://github.com/Kevin-De-Koninck/Get-It/blob/14a2f4077f5f218d969c1eb7a3a1a8e3b34cf165/Get%20It/GetIt.swift#L21

**Comment by bhargavgv** [comment]
It probably does check (maybe the checking code looks in the wrong place), but the real problem is that it locks out all of the functionality (you can't even *try* downloading) unless it sees the dependencies.

**Comment by koderian** [comment]
@bhargavgv I tried this too, got same result ): 

hopefully this gets fixed **sooon**

**Comment by Kevin-De-Koninck** [comment]
Late to the party... Broke my hand last night so now I got the time! I'm sorry for the long wait. I'll be fixing most issues in the coming days (as many as I can).

**Comment by Kevin-De-Koninck** [comment]
pretty sure I coded a bug 😋 will fix it

**Comment by Kevin-De-Koninck** [comment]
I removed the code that checks it all together... the more lines of code, the more bugs and I don't have the time to feed my bugs 😉 I'll add a list of dependencies to the readme

**Comment by Kevin-De-Koninck** [comment]
@killedora @bhargavgv ; I hope your issues are solved now. I'll close this issue for now but reopen it if it didn't fix it for you (I'll upload version 3 soon that will contain the fixes)

**Comment by Kevin-De-Koninck** [comment]
New version available here:
https://github.com/Kevin-De-Koninck/Get-It/releases/tag/v0.7
