### ISSUE TITLE
It doesn't work, since it downloaded and installed with all dependencies. Help!

### ISSUE THREAD

**Issue by keepry** [Kevin-De-Koninck/Get-It#14]
I tried many individual YouTube videos and playlists, none of them could be downloaded successfully. Just like https://www.youtube.com/watch?v=cZx0jGmYH5c and so. 
I'm seemed just not able to use Get It, the Wiki is short and no explaining much.

$ cat /tmp/getit_logs

[PROGRESS VIEW]	Gathering information: Please wait
[COMMAND]	export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin && youtube-dl --newline --prefer-ffmpeg --yes-playlist --extract-audio --youtube-skip-dash-manifest --max-filesize 15M --ignore-errors --audio-format mp3 --audio-quality 5 --sub-format srt -o ~/Downloads//%(title)s.%(ext)s  https://www.youtube.com/watch?v=cZx0jGmYH5c  2>&1
[RECEIVED]	  File /usr/local/bin/youtube-dl, line 2
SyntaxError: Non-ASCII character ? in file /usr/local/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

[PROGRESS VIEW]	Failed...: Something went wrong. Please try other settings or report this issue on github if the problem doesnt magically disappears.

**Comment by Kevin-De-Koninck** [comment]
Hi,
I’ll take a look at this as soon as I have Some spare time. I’ll update you when I’m done.

Thanks in advance for the logs!

**Comment by koderian** [comment]
Same! @cheapasyou 

Please FIX! @Kevin-De-Koninck

**Comment by Kevin-De-Koninck** [comment]
Late to the party... Broke my hand last night so now I got the time! I'm sorry for the long wait. I'll be fixing most issues in the coming days (as many as I can).

**Comment by Kevin-De-Koninck** [comment]
always update youtube-dl, that might help (the error is for youtube-dl itself)

soon I'll upload a new version and then you can go to settings and cilck the update button to update all dependencies, or issue the following command in the terminal app:
```
brew upgrade youtube-dl
```

**Comment by Kevin-De-Koninck** [comment]
New version available here:
https://github.com/Kevin-De-Koninck/Get-It/releases/tag/v0.7

@killedora @cheapasyou  Can you verify?
