### ISSUE TITLE
App says "something went wrong"

### ISSUE THREAD

**Issue by adamj02090830** [Kevin-De-Koninck/Get-It#25]
[PROGRESS VIEW]	Gathering information: Please wait
[COMMAND]	export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin && youtube-dl --newline --prefer-ffmpeg --yes-playlist --playlist-reverse --username adamj02090830 --password tanakh12% --format 37 --youtube-skip-dash-manifest --write-sub --ignore-errors --audio-format mp3 --audio-quality 5 --sub-format srt -o /Volumes/Seagate Por/Private/Get It/%(playlist)s/%(title)s.%(ext)s  https://www.youtube.com/channel/UCNye-wNBqNL5ZzHSJj3l8Bg  2>&1
[RECEIVED]	ERROR: fixed output name but more than one file to download

[PROGRESS VIEW]	Failed...: Something went wrong. Please try other settings or report this issue on github if the problem doesnt magically disappears.

**Comment by Kevin-De-Koninck** [comment]
Try updating youtube-dl in the Terminal:
```
sudo youtube-dl --update
```

**Comment by Kevin-De-Koninck** [comment]
https://github.com/Kevin-De-Koninck/Get-It#common-issues
