### ISSUE TITLE
How to fully uninstall?

### ISSUE THREAD

**Issue by rvb3n** [Kevin-De-Koninck/Get-It#26]
Hi, first of all thank you for your work!
I need to clean my system so can you tell me how to do a full uninstall?
How do I remove all the dependencies installed by the app?

- xcode-select
- brew
- python
- python3
- pycrypt
- youtube-dl
- libav
- ffmpeg

**Comment by Kevin-De-Koninck** [comment]
All brew packages and brew can be uninstalled as follows:
https://github.com/Homebrew/install#uninstall-homebrew

Command line tools can be uninstalled as follows:
```
sudo rm -rf /Library/Developer/CommandLineTools
```

Note that this will remove everything that once was installed with brew
