### ISSUE TITLE
No go

### ISSUE THREAD

**Issue by rgosens2** [Kevin-De-Koninck/Get-It#29]
On BigSur 11.0.1

God, open source sucks.

**Comment by Kevin-De-Koninck** [comment]
An advantage of open source is that you can submit a PR to improve the code or support a newer OS. I'd happily approve a review. Else I expect a more detailed error report on what needs to happen to support the new OS and I'll implement it when I got some spare time. But unfortunately, I cannot ask God why it didn't work for you.

I will look at it as soon as I got some spare time, I'm not getting paid for this, so I don't prioritize this as much.
