### ISSUE TITLE
Invisible download button

### ISSUE THREAD

**Issue by seigoterao** [Kevin-De-Koninck/Get-It#4]
Hello. I know this is not a "big issue" but the download button on this app is invisible. I am currently running High Sierra. If this is a small problem that can be fixed easily, it would be great. 

https://imgur.com/a/oQSFL

Thank you.

**Comment by Kevin-De-Koninck** [comment]
It's a pretty big issue if you can't click the download button.
I will see in the upcoming days if I have the same problem and implement a fix. I'll update you once this has been fixed.

Thanks for reporting this!

**Comment by wlcode2017** [comment]
Who are you?I think weather you get wrong email address




| |
小逝
邮箱：15950593878@163.com
|

签名由 网易邮箱大师 定制

On 04/12/2018 16:26, Kevin De Koninck wrote:

It's a pretty big issue if you can't click the download button.
I will see in the upcoming days if I have the same problem and implement a fix. I'll update you once this has been fixed.

Thanks for reporting this!

**Comment by michellekg** [comment]
Same here, cannot use it because of the invisible button.

**Comment by Kevin-De-Koninck** [comment]
I fixed the bug and you can download the new app [here](https://github.com/Kevin-De-Koninck/Get-It/releases/tag/0.5.4)

Can you guys verify?

-------

I also saw that a lot has changed since I last used Swift and I'll have to update all my apps...

Please note that there is another bug: https://github.com/Kevin-De-Koninck/Get-It/issues/6
The downloading does work, but you just can't see the progress bar this way... I'll see what I can do in the upcoming weeks

**Comment by seigoterao** [comment]
Hello. Thank you for the quick fix! I can confirm that the download button is visible now. However, I also see a new bug in this build. In the previous version, while the overlay was blank just like the new build, the overlay would go away once the download was finished. In this new version, however, the overlay seems to get "stuck" even after the download has finished. I have confirmed this on both video and mp3 downloads. This overlay prevents the user from making further interactions with the app.

https://imgur.com/IS9UcBo

**Comment by Kevin-De-Koninck** [comment]
Yes, This has the same reason as bug #6 
The software that I used to display the overlay is not maintained anymore and the latest macOS update kind of messed with it.

I will implement a quick fix within 24h from now, and when I have some more spare time, I'll implement a new way of showing the status.

Please view #6 for any update on this. I will close this bug as it is resolved
