### ISSUE TITLE
Replace pod DJProgressHUD_OSX

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [Kevin-De-Koninck/Get-It#6]
https://github.com/danielmj/DJProgressHUD_OSX

The pod isn't maintained anymore. replace this by a version that is maintained.

The pod was used tho show a pop-over view that displays the download status. Now it only shows a gray view.

**Comment by Kevin-De-Koninck** [comment]
@seigoterao I implemented my own progress indicator (really quick). Hopefully this will also solve that other bug that you experienced in #4 

The new version can be found here
https://github.com/Kevin-De-Koninck/Get-It/releases/tag/0.5.5

PS: I have not tested this completely

**Comment by seigoterao** [comment]
@Kevin-De-Koninck It is working perfectly now. Thank you so much!
