### ISSUE TITLE
No visible download button

### ISSUE THREAD

**Issue by NightMachinery** [Kevin-De-Koninck/Get-It#8]
![image](https://user-images.githubusercontent.com/36224762/39210815-0fdc1a08-481f-11e8-9a91-570d222e03ab.png)

The button is clickable, though, and results in this:
![image](https://user-images.githubusercontent.com/36224762/39210846-2414db0e-481f-11e8-9489-bd583c476f33.png)

**Comment by Kevin-De-Koninck** [comment]
Ah yes, this was issue #4 and #6. This has been fixed but the link in the readme file was not updated. This has been fixed. (or click [here](https://github.com/Kevin-De-Koninck/Get-It/releases/download/0.5.5/Get.It.app.zip) to download the fixed version)

You'll now get something like this:
<img width="444" alt="screen shot 2018-04-24 at 22 02 44" src="https://user-images.githubusercontent.com/9513994/39211301-7d618fa4-480b-11e8-8348-a71b54d5d5a5.png">
